# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfhistory', '0020_auto_20151215_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='duration',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
