# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfhistory', '0021_auto_20151222_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='duration',
            new_name='duration_minutes',
        ),
    ]
