# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfhistory', '0022_auto_20151222_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='duration_minutes',
            field=models.FloatField(),
        ),
    ]
