# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfhistory', '0023_auto_20151222_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='failurecount',
            new_name='failure_count',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='successcount',
            new_name='success_count',
        ),
        migrations.AddField(
            model_name='transaction',
            name='failure_qps',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='success_qps',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
