# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfhistory', '0027_result_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='average',
            new_name='responsetime_average',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='maximum',
            new_name='responsetime_maximum',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='median',
            new_name='responsetime_median',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='minimum',
            new_name='responsetime_minimum',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='p90',
            new_name='responsetime_p90',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='p95',
            new_name='responsetime_p95',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='p99',
            new_name='responsetime_p99',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='p99_99',
            new_name='responsetime_p99_99',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='stddev',
            new_name='responsetime_stddev',
        ),
    ]
