# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfhistory', '0029_auto_20160212_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='latency_average',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='latency_maximum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='latency_median',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='latency_minimum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='latency_p90',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='latency_p95',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='latency_p99',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='latency_p99_99',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='latency_stddev',
            field=models.FloatField(null=True),
        ),
    ]
